name: Classroom Autograding

on:
  push:
  pull_request:

jobs:
  autograding:
    runs-on: ubuntu-latest
    env:
      RUN_ASSIGNMENT_TESTS: "1"
      STUDENT_ID: ${{ github.actor }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run GitHub Classroom Autograding
        uses: education/autograding@v1

